name: helloWorld

on:
  workflow_dispatch:
    inputs:
      pokemon-name:
        description: 'name of pokemon'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: get-pokemon
        env: 
          POKEMON: ${{ inputs.pokemon-name }}
        run: |
          curl https://pokeapi.co/api/v2/pokemon/${POKEMON} | jq '.abilities[].ability' 
